# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coala/pb/client_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from coala.pb import common_pb2 as coala_dot_pb_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x63oala/pb/client_service.proto\x12\x08\x63oala.pb\x1a\x15\x63oala/pb/common.proto\"\x83\x01\n\x0eOperateRequest\x12%\n\x04type\x18\x01 \x01(\x0e\x32\x17.coala.pb.OperationType\x12\r\n\x05model\x18\x02 \x01(\x0c\x12\x12\n\ndata_index\x18\x03 \x01(\x05\x12\'\n\x06\x63onfig\x18\x04 \x01(\x0b\x32\x17.coala.pb.OperateConfig\"\xcd\x01\n\rOperateConfig\x12\x12\n\nbatch_size\x18\x01 \x01(\x05\x12\x13\n\x0blocal_epoch\x18\x02 \x01(\x05\x12\x0c\n\x04seed\x18\x03 \x01(\x03\x12&\n\toptimizer\x18\x04 \x01(\x0b\x32\x13.coala.pb.Optimizer\x12\x12\n\nlocal_test\x18\x05 \x01(\x08\x12\x0f\n\x07task_id\x18\x06 \x01(\t\x12\x10\n\x08round_id\x18\x07 \x01(\x05\x12\r\n\x05track\x18\x08 \x01(\x08\x12\x17\n\x0ftest_batch_size\x18\t \x01(\x05\"7\n\tOptimizer\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02lr\x18\x02 \x01(\x02\x12\x10\n\x08momentum\x18\x03 \x01(\x02\"3\n\x0fOperateResponse\x12 \n\x06status\x18\x01 \x01(\x0b\x32\x10.coala.pb.Status*4\n\rOperationType\x12\x11\n\rOP_TYPE_TRAIN\x10\x00\x12\x10\n\x0cOP_TYPE_TEST\x10\x01\x32Q\n\rClientService\x12@\n\x07Operate\x12\x18.coala.pb.OperateRequest\x1a\x19.coala.pb.OperateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coala.pb.client_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERATIONTYPE']._serialized_start=518
  _globals['_OPERATIONTYPE']._serialized_end=570
  _globals['_OPERATEREQUEST']._serialized_start=67
  _globals['_OPERATEREQUEST']._serialized_end=198
  _globals['_OPERATECONFIG']._serialized_start=201
  _globals['_OPERATECONFIG']._serialized_end=406
  _globals['_OPTIMIZER']._serialized_start=408
  _globals['_OPTIMIZER']._serialized_end=463
  _globals['_OPERATERESPONSE']._serialized_start=465
  _globals['_OPERATERESPONSE']._serialized_end=516
  _globals['_CLIENTSERVICE']._serialized_start=572
  _globals['_CLIENTSERVICE']._serialized_end=653
# @@protoc_insertion_point(module_scope)
